name: ブランドリポジトリ取得+サイトマップ生成
# cron-jobを作成してIDをどうやって管理するか

on:
  workflow_dispatch:
    inputs:
      repository:
        type: choice
        description: "対象ブランド"
        required: true
        options:
          - "topards.jp"
          - "feliamo.jp"
          - "molak.jp"
          - "ns-collection.jp"
          - "lilmoon.jp"
          - "minette-lens.jp"
          - "mirage-c.jp"
          - "mimuco.jp"
          - "harne.jp"
          - "louer.jp"
          - "lumieu.jp"
          - "puuuuchu.jp"
          - "melady.jp"
          - "melloew.jp"
          - "faloom.jp"
          - "mimicharme.jp"
          - "lensbe.jp"
          - "clainel.jp"
          - "chapun.jp"
          - "resay.jp"
          - "michou.jp"
      repository_no_register:
        description: "未登録のブランドリポジトリ"
        default: ""

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  CreateBranch:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      REPOSITORY_PATH: ${{ steps.set_branch_name.outputs.path }}

    steps:
      - uses: actions/checkout@v4
      - name: Create new branch
        id: set_branch_name
        run: |
          echo "path=release/github_${{ github.run_id }}" >> $GITHUB_ENV
          echo "path=release/github_${{ github.run_id }}" >> $GITHUB_OUTPUT
          git checkout -b $path
      - name: Push new branch
        run: |
          git push -u origin $path

  UpdateSubmodules:
    needs: CreateBranch
    uses: ./.github/workflows/update_submodules.yml
    with:
      repository: ${{ inputs.repository }}
      repository_no_register: ${{ inputs.repository_no_register }}
      branch_name: ${{ needs.CreateBranch.outputs.REPOSITORY_PATH }}
    secrets:
      GITHUB_TOKEN_VALUE: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  CreateSiteMap:
    needs: UpdateSubmodules
    uses: ./.github/workflows/create_sitemap.yml
    with:
      repository: ${{ inputs.repository }}
      repository_no_register: ${{ inputs.repository_no_register }}
      branch_name: ${{ needs.CreateBranch.outputs.REPOSITORY_PATH }}
    secrets:
      GITHUB_TOKEN_VALUE: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  DeleteBranch:
    needs: CreateSiteMap
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch
        if: needs.UpdateSubmodules.outputs.changed_files == 'false'
        run: git push origin --delete ${{ needs.CreateBranch.outputs.REPOSITORY_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_VALUE }}

  CreatePR:
    needs: CreateSiteMap
    runs-on: ubuntu-latest
    steps:
      - name: Create PR
        if: needs.UpdateSubmodules.outputs.changed_files == 'true'
        run: gh pr create --fill
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  AutoMerge:
    needs: CreatePR
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge PR
        if: needs.UpdateSubmodules.outputs.changed_files == 'true'
        run: gh pr merge --auto --merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
