name: 00.納品ファイルの取得と公開予約
# ブランドリポジトリ取得+サイトマップ生成
# cron-jobを作成してIDをどうやって管理するか

on:
  workflow_dispatch:
    inputs:
      repository:
        type: choice
        description: "対象ブランド"
        required: true
        options:
          - "topards.jp"
          - "feliamo.jp"
          - "molak.jp"
          - "ns-collection.jp"
          - "lilmoon.jp"
          - "minette-lens.jp"
          - "mirage-c.jp"
          - "mimuco.jp"
          - "harne.jp"
          - "louer.jp"
          - "lumieu.jp"
          - "puuuuchu.jp"
          - "melady.jp"
          - "melloew.jp"
          - "faloom.jp"
          - "mimicharme.jp"
          - "lensbe.jp"
          - "clainel.jp"
          - "chapun.jp"
          - "resay.jp"
          - "michou.jp"
      repository_no_register:
        description: "未登録のブランドリポジトリ"
        default: ""
      reservation:
        type: boolean
        description: 予約設定
        default: false
      month:
        type: choice
        required: false
        description: 月
        options:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
      day:
        type: choice
        required: false
        description: 日
        options:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
          - 13
          - 14
          - 15
          - 16
          - 17
          - 18
          - 19
          - 20
          - 21
          - 22
          - 23
          - 24
          - 25
          - 26
          - 27
          - 28
          - 29
          - 30
          - 31
      hour:
        type: choice
        required: false
        description: 時間
        options:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
          - 13
          - 14
          - 15
          - 16
          - 17
          - 18
          - 19
          - 20
          - 21
          - 22
          - 23
      minutes:
        type: choice
        required: false
        description: 分
        options:
          - 00
          - 05
          - 10
          - 15
          - 20
          - 25
          - 30
          - 35
          - 40
          - 45
          - 50
          - 55

permissions:
  contents: write
  pull-requests: write

jobs:
  # このジョブは、ワークフローを実行するユーザーが許可されたリストに含まれているかどうかを確認します。
  # 許可されていない場合、ワークフローは警告を出して終了します。
  # 許可されている場合、ワークフローは続行されます。
  Auth:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Check if the user is authorized
        env:
          USER_LOGIN: ${{ github.actor }}
          CODE_OWNERS: ${{ vars.CODE_OWNERS }}
        run: |
          echo "$USER_LOGIN が許可されたリストに含まれているか確認しています..."
          if ! echo "$CODE_OWNERS" | grep -q -w "$USER_LOGIN"; then
            echo "ユーザー $USER_LOGIN はこのワークフローを実行する権限がありません。"
            echo "::warning:: ユーザー $USER_LOGIN はこのワークフローを実行する権限がありません。"
            exit 1
          fi
          echo "ユーザー $USER_LOGIN は認証されました。続行します..."

      # Jobが落ちた場合のみ、Playbookを実行する
      - name: Playbook
        if: failure()
        uses: ./.github/actions/playbook
        with:
          message: |
            # ${{ github.job }} が失敗しました

            ## 影響
            - 何が影響を受けるか

            ## 調査方法
            - Jobの落ちてるステップのエラーログを確認してください

            ## 修正方法
            - どのように対応するか

            ## 修正後の確認方法
            - 修正後にどのように確認するか

  # このジョブは、新しいリリースブランチを作成し、リモートリポジトリにプッシュするためのものです。
  # 'Auth' ジョブが完了した後に実行されます。
  # ジョブの出力として、作成されたリリースブランチの名前を提供します。
  CreateBranch:
    needs: Auth
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
      - name: Push new branch
        run: |
          git checkout -b release/github_${{ github.run_id }}
          git push -u origin release/github_${{ github.run_id }}

  UpdateSubmodules:
    needs: CreateBranch
    uses: ./.github/workflows/update_submodules.yml
    with:
      repository: ${{ inputs.repository }}
      repository_no_register: ${{ inputs.repository_no_register }}
      branch_name: release/github_${{ github.run_id }}
    secrets:
      GITHUB_TOKEN_VALUE: ${{ secrets.PERSONAL_ACCESS_TOKEN }}





  DEBUG:
    needs: UpdateSubmodules
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: release/github_${{ github.run_id }}
      - run: |
          ls -a
          echo ""
          git branch -a

      - name: Checkout branch
        run: |
          git checkout ${{ inputs.branch_name }}

      # COMMIT_MESSAGE=$(git log -1 --pretty=%s)
      - name: Get commit message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "Commit message: $COMMIT_MESSAGE"






  CreateSiteMap:
    needs: UpdateSubmodules
    if: ${{ contains(github.event.head_commit.message, 'Automatically update submodules') }}
    uses: ./.github/workflows/create_sitemap.yml
    with:
      repository: ${{ inputs.repository }}
      repository_no_register: ${{ inputs.repository_no_register }}
      branch_name: release/github_${{ github.run_id }}
    secrets:
      GITHUB_TOKEN_VALUE: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  # このジョブは、指定されたブランチが存在しない場合にそのブランチをリモートリポジトリから削除するためのものです。
  # 具体的には、UpdateSubmodulesジョブの出力がfalseの場合に、CreateBranchジョブで作成されたブランチを削除します。
  DeleteBranch:
    needs: UpdateSubmodules
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Delete branch
        if: ${{ !contains(github.event.head_commit.message, 'Automatically update submodules') }}
        run: git push origin --delete release/github_${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # このジョブは、リポジトリをチェックアウトし、指定されたブランチに切り替え、
  # コミットが存在する場合にプルリクエストを作成します。
  CloseBranch:
    needs: CreateSiteMap
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: release/github_${{ github.run_id }}

      - name: Create PR if commit exists
        run: |
          gh pr create --fill
          PR_NUMBER=$(gh pr list --state open --head develop --base main --json number --jq '.[].number')
          if [ -n "$PR_NUMBER" ]; then
            gh pr merge $PR_NUMBER --merge --auto
          else
            echo "::error:: Mergeするプルリクエストが見つかりません。"
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # UploadReservation:
  #   needs: [CreateSiteMap, DeleteBranch]
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 1

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
