name: ブランドリポジトリ取得+サイトマップ生成

on:
  workflow_dispatch:
    inputs:
      repository:
        type: choice
        description: "対象ブランド"
        required: true
        options:
          - "topards.jp"
          - "feliamo.jp"
          - "molak.jp"
          - "ns-collection.jp"
          - "lilmoon.jp"
          - "minette-lens.jp"
          - "mirage-c.jp"
          - "mimuco.jp"
          - "harne.jp"
          - "louer.jp"
          - "lumieu.jp"
          - "puuuuchu.jp"
          - "melady.jp"
          - "melloew.jp"
          - "faloom.jp"
          - "mimicharme.jp"
          - "lensbe.jp"
          - "clainel.jp"
          - "chapun.jp"
          - "resay.jp"
          - "michou.jp"
      repository_no_register:
        description: "対象ブランド（未登録）"
        default: ""

permissions:
  contents: write
  id-token: write
  pull-requests: write
  actions: read


jobs:
  CreateBranch:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
      - name: Create new branch
        run: |
          git checkout -b release/github_${{ github.run_id }}
      - name: Push new branch
        run: |
          git push -u origin release/github_${{ github.run_id }}

  UpdateSubmodules:
    uses: ./.github/workflows/update_submodules.yml
    with:
      repository: ${{ inputs.repository }}
      repository_no_register: ${{ inputs.repository_no_register }}
      branch_name: ${{ github.run_id }}
    secrets:
      GITHUB_TOKEN_VALUE: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  CreateSiteMap:
    needs: UpdateSubmodules
    uses: ./.github/workflows/create_sitemap.yml
    with:
      repository: ${{ inputs.repository }}
      repository_no_register: ${{ inputs.repository_no_register }}

  merge:
    needs: CreateSiteMap
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Create PR
        if: ${{ steps.commit.outputs.changed_files == 'true' }}
        run: |
          gh pr create --fill
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Auto-merge PR
        if: ${{ steps.commit.outputs.changed_files == 'true' }}
        run: gh pr merge --auto --merge
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
