name: ブランドリポジトリ取得+サイトマップ生成

on:
  workflow_dispatch:
    inputs:
      repository:
        type: choice
        description: "対象ブランド"
        required: true
        options:
          - "topards.jp"
          - "feliamo.jp"
          - "molak.jp"
          - "ns-collection.jp"
          - "lilmoon.jp"
          - "minette-lens.jp"
          - "mirage-c.jp"
          - "mimuco.jp"
          - "harne.jp"
          - "louer.jp"
          - "lumieu.jp"
          - "puuuuchu.jp"
          - "melady.jp"
          - "melloew.jp"
          - "faloom.jp"
          - "mimicharme.jp"
          - "lensbe.jp"
          - "clainel.jp"
          - "chapun.jp"
          - "resay.jp"
          - "michou.jp"
      repository_no_register:
        description: "対象ブランド（未登録）"
        default: ""

permissions:
  contents: write
  id-token: write
  pull-requests: write
  actions: read

jobs:
  CreateBranch:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      RELEASE_BRANCH_NAME: release/github_${{ github.run_id }}

    steps:
      - uses: actions/checkout@v4
      - name: Create new branch
        run: |
          git checkout -b ${{ env.RELEASE_BRANCH_NAME }}
      - name: Push new branch
        run: |
          git push -u origin ${{ env.RELEASE_BRANCH_NAME }}

  UpdateSubmodules:
    needs: CreateBranch
    uses: ./.github/workflows/update_submodules.yml
    with:
      repository: ${{ inputs.repository }}
      repository_no_register: ${{ inputs.repository_no_register }}
      branch_name: ${{ env.RELEASE_BRANCH_NAME }}
    secrets:
      GITHUB_TOKEN_VALUE: ${{ secrets.GITHUB_TOKEN }}

  CreateSiteMap:
    needs: UpdateSubmodules
    uses: ./.github/workflows/create_sitemap.yml
    with:
      repository: ${{ inputs.repository }}
      repository_no_register: ${{ inputs.repository_no_register }}
      branch_name: ${{ env.RELEASE_BRANCH_NAME }}
    secrets:
      GITHUB_TOKEN_VALUE: ${{ secrets.GITHUB_TOKEN }}

  CreatePR:
    needs: CreateSiteMap
    runs-on: ubuntu-latest
    steps:
      - name: Create PR
        if: needs.UpdateSubmodules.outputs.changed_files == 'true'
        run: gh pr create --fill
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  AutoMerge:
    needs: CreatePR
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge PR
        if: needs.UpdateSubmodules.outputs.changed_files == 'true'
        run: gh pr merge --auto --merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  DeleteBranch:
    needs: UpdateSubmodules
    runs-on: ubuntu-latest
    if: needs.UpdateSubmodules.outputs.changed_files == 'false'
    steps:
      - name: Delete branch
        run: |
          git push origin --delete ${{ env.RELEASE_BRANCH_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
