name: 01.納品ファイルの取得と公開予約

on:
  workflow_dispatch:
    inputs:
      repository:
        type: choice
        description: "対象ブランド"
        required: true
        options:
          - "topards.jp"
          - "feliamo.jp"
          - "molak.jp"
          - "ns-collection.jp"
          - "lilmoon.jp"
          - "minette-lens.jp"
          - "mirage-c.jp"
          - "mimuco.jp"
          - "harne.jp"
          - "louer.jp"
          - "lumieu.jp"
          - "puuuuchu.jp"
          - "melady.jp"
          - "melloew.jp"
          - "faloom.jp"
          - "mimicharme.jp"
          - "lensbe.jp"
          - "clainel.jp"
          - "chapun.jp"
          - "resay.jp"
          - "michou.jp"
      repository_no_register:
        description: "任意のブランドリポジトリ"
        default: ""
      reservation:
        type: boolean
        description: 予約設定
        default: false
      month:
        type: choice
        required: false
        description: 月
        options:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
      day:
        type: choice
        required: false
        description: 日
        options:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
          - 13
          - 14
          - 15
          - 16
          - 17
          - 18
          - 19
          - 20
          - 21
          - 22
          - 23
          - 24
          - 25
          - 26
          - 27
          - 28
          - 29
          - 30
          - 31
      hour:
        type: choice
        required: false
        description: 時間
        options:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
          - 13
          - 14
          - 15
          - 16
          - 17
          - 18
          - 19
          - 20
          - 21
          - 22
          - 23
      minutes:
        type: choice
        required: false
        description: 分
        options:
          - 00
          - 05
          - 10
          - 15
          - 20
          - 25
          - 30
          - 35
          - 40
          - 45
          - 50
          - 55

permissions:
  contents: write
  pull-requests: write

env:
  REVIEWER: github-actions[bot]

jobs:
  # このジョブは、ワークフローを実行するユーザーが許可されたリストに含まれているかどうかを確認します。
  # 許可されていない場合、ワークフローは警告を出して終了します。
  # 許可されている場合、ワークフローは続行されます。
  Auth:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Check if the user is authorized
        env:
          USER_LOGIN: ${{ github.actor }}
          CODE_OWNERS: ${{ vars.CODE_OWNERS }}
        run: |
          echo "$USER_LOGIN が許可されたリストに含まれているか確認しています..."
          if ! echo "$CODE_OWNERS" | grep -q -w "$USER_LOGIN"; then
            echo "ユーザー $USER_LOGIN はこのワークフローを実行する権限がありません。"
            echo "::warning:: ユーザー $USER_LOGIN はこのワークフローを実行する権限がありません。"
            exit 1
          fi
          echo "ユーザー $USER_LOGIN は認証されました。続行します..."

  # このジョブは、新しいリリースブランチを作成し、リモートリポジトリにプッシュするためのものです。
  # 'Auth' ジョブが完了した後に実行されます。
  # ジョブの出力として、作成されたリリースブランチの名前を提供します。
  CreateBranch:
    needs: Auth
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
      - name: Push new branch
        run: |
          git checkout -b release/github_${{ github.run_id }}
          git push -u origin release/github_${{ github.run_id }}

  UpdateSubmodules:
    needs: CreateBranch
    uses: ./.github/workflows/update_submodules.yml
    with:
      repository: ${{ inputs.repository }}
      repository_no_register: ${{ inputs.repository_no_register }}
      branch_name: release/github_${{ github.run_id }}
    secrets:
      GITHUB_TOKEN_VALUE: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  UpdateStatus:
    needs: UpdateSubmodules
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      COMMIT_MESSAGE: ${{ steps.get_commit_message.outputs.COMMIT_MESSAGE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: release/github_${{ github.run_id }}

      - name: Get commit message
        id: get_commit_message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%s | xargs)
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
          echo "$COMMIT_MESSAGE"

  CreateSiteMap:
    needs: UpdateStatus
    if: ${{ needs.UpdateStatus.outputs.COMMIT_MESSAGE && needs.UpdateStatus.outputs.COMMIT_MESSAGE == 'Automatically update submodules' }}
    uses: ./.github/workflows/create_sitemap.yml
    with:
      repository: ${{ inputs.repository }}
      repository_no_register: ${{ inputs.repository_no_register }}
      branch_name: release/github_${{ github.run_id }}
    secrets:
      GITHUB_TOKEN_VALUE: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  # このジョブは、指定されたブランチが存在しない場合にそのブランチをリモートリポジトリから削除するためのものです。
  # 具体的には、UpdateSubmodulesジョブの出力がfalseの場合に、CreateBranchジョブで作成されたブランチを削除します。
  DeleteBranch:
    needs: UpdateStatus
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: ${{ needs.UpdateStatus.outputs.COMMIT_MESSAGE && needs.UpdateStatus.outputs.COMMIT_MESSAGE != 'Automatically update submodules' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Delete branch
        run: git push origin --delete release/github_${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # このジョブは、リポジトリをチェックアウトし、指定されたブランチに切り替え、
  # コミットが存在する場合にプルリクエストを作成します。
  CloseBranch:
    needs: CreateSiteMap
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: release/github_${{ github.run_id }}
          fetch-depth: 0

      - name: check PR
        id: check_pr
        run: |
          echo "count=$(gh pr list -B release/github_${{ github.run_id }} -H ${{ github.ref_name }} --json 'id' -q '.[] | length')" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR
        if: ${{ steps.check_pr.outputs.count == '' }}
        run: |
          gh pr create --fill --base main --head release/github_${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set required check
        run: gh api \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -X POST /repos/${{ github.repository }}/statuses/${{ github.sha }} \
          -f state=success \
          -f context="Dummy Required Check"

      - name: Auto-merge PR
        run: gh pr merge --auto --merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # CreateTag:
  #   needs: CloseBranch
  #   uses: ./.github/workflows/create_tag.yml
  #   with:
  #     repository: ${{ inputs.repository }}
  #     repository_no_register: ${{ inputs.repository_no_register }}

  UploadReservation_c:
    needs: CreateSiteMap
    if: inputs.reservation == true
    uses: ./.github/workflows/reservation.yml
    with:
      repository: ${{ inputs.repository }}
      month: ${{ inputs.month }}
      day: ${{ inputs.day }}
      hour: ${{ inputs.hour }}
      minutes: ${{ inputs.minutes }}
    secrets:
      CRON_JOB_TOKEN_VALUE: ${{ secrets.CRON_JOB_TOKEN }}

  UploadReservation_d:
    needs: DeleteBranch
    if: inputs.reservation == true
    uses: ./.github/workflows/reservation.yml
    with:
      repository: ${{ inputs.repository }}
      month: ${{ inputs.month }}
      day: ${{ inputs.day }}
      hour: ${{ inputs.hour }}
      minutes: ${{ inputs.minutes }}
    secrets:
      CRON_JOB_TOKEN_VALUE: ${{ secrets.CRON_JOB_TOKEN }}
