name: ブランドリポジトリ取得+サイトマップ生成

on:
  workflow_dispatch:
    inputs:
      repository:
        type: choice
        description: "対象ブランド"
        required: true
        options:
          - "topards.jp"
          - "feliamo.jp"
          - "molak.jp"
          - "ns-collection.jp"
          - "lilmoon.jp"
          - "minette-lens.jp"
          - "mirage-c.jp"
          - "mimuco.jp"
          - "harne.jp"
          - "louer.jp"
          - "lumieu.jp"
          - "puuuuchu.jp"
          - "melady.jp"
          - "melloew.jp"
          - "faloom.jp"
          - "mimicharme.jp"
          - "lensbe.jp"
          - "clainel.jp"
          - "chapun.jp"
          - "resay.jp"
          - "michou.jp"
      repository_no_register:
        description: "対象ブランド（未登録）"
        default: ""

permissions:
  contents: write
  id-token: write
  pull-requests: write
  actions: read

env:
  RELEASE_BRANCH_NAME: ${{ github.run_id }}

jobs:
  UpdateSubmodules:
    uses: ./.github/workflows/update_submodules.yml
    with:
      repository: ${{ inputs.repository }}
      repository_no_register: ${{ inputs.repository_no_register }}
    secrets:
      TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  CreateSiteMap:
    needs: UpdateSubmodules
    uses: ./.github/workflows/create_sitemap.yml
    with:
      repository: ${{ inputs.repository }}
      repository_no_register: ${{ inputs.repository_no_register }}

  merge:
    needs: CreateSiteMap
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Merge
        run: |
          git checkout main
          git merge --no-ff release/github_${{ env.RELEASE_BRANCH_NAME }}
          git push origin main
