name: CD

on:
  pull_request:
    branches:
      - main
    types:
      - closed

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  SYSTEM: ${{ vars.SYSTEM }}
  DEV_AWS_ACCOUNT_ID: ${{ secrets.DEV_AWS_ACCOUNT_ID }}
  PROD_AWS_ACCOUNT_ID: ${{ secrets.PROD_AWS_ACCOUNT_ID }}

permissions:
  contents: read
  id-token: write
  pull-requests: write
  actions: read

jobs:
  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.2.2
        with:
          ref: main
          fetch-depth: 0

      - name: Create new branch
        run: |
          git checkout -b release/github_${{ env.RELEASE_BRANCH_NAME }}

      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     cache: npm
      #     node-version: "23.2.0"

      # - uses: actions/cache@v4
      #   id: cache
      #   with:
      #     path: node_modules
      #     key: ${{ runner.arch }}-${{ runner.os }}-node-${{ steps.setup_node.outputs.node-version }}-npm-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.arch }}-${{ runner.os }}-node-${{ steps.setup_node.outputs.node-version }}-npm-

      # - name: Install dependencies
      #   if: steps.cache.outputs.cache-hit != 'true'
      #   run: npm ci --no-audit --progress=false --silent

      # out フォルダを作成し、public フォルダ内のすべてのファイルをコピー
      - name: Copy Files
        run: |
          mkdir out
          cp -R test-admin_submoduleA/* out/

      # - name: include sitemap
      #   uses: ./.github/workflow/_create_sitemap
