name: 07.Cron設定と公開状況の確認

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Cron:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: 登録情報の取得
        env:
          CRON_JOB_TOKEN: ${{ secrets.CRON_JOB_TOKEN }}
        run: |
          response=$(curl -s -X GET \
            -H "Authorization: Bearer $CRON_JOB_TOKEN" \
            https://api.cron-job.org/jobs) || { echo "::error:: CRONジョブの取得に失敗しました。"; echo "エラーログ: $(curl -s -X GET -H "Authorization: Bearer $CRON_JOB_TOKEN" https://api.cron-job.org/jobs)"; exit 1; }

          # jobIdとtitleを配列として格納
          jobIds=($(echo "$response" | jq -r '.jobs[].jobId'))
          titles=($(echo "$response" | jq -r '.jobs[].title'))
          enabled=($(echo "$response" | jq -r '.jobs[].enabled'))
          hours=($(echo "$response" | jq -r '.jobs[].schedule.hours | join(",")'))
          mdays=($(echo "$response" | jq -r '.jobs[].schedule.mdays | join(",")'))
          minutes=($(echo "$response" | jq -r '.jobs[].schedule.minutes | join(",")'))
          months=($(echo "$response" | jq -r '.jobs[].schedule.months | join(",")'))
          timezones=($(echo "$response" | jq -r '.jobs[].schedule.timezone'))

          echo "# 処理結果"
          {
            echo "| CRON ID | ドメイン | 予約状況 | 予約時間 |"
            echo "| --- | --- | --- | --- |"
            for i in "${!jobIds[@]}"; do
              if [ "${enabled[$i]}" = "true" ]; then
                schedule_display="${timezones[$i]} ${months[$i]}月${mdays[$i]}日${hours[$i]}時${minutes[$i]}分"
              else
                schedule_display="--"
              fi

              echo "| ${jobIds[$i]} | ${titles[$i]} | ${enabled[$i]} | ${schedule_display} |"
            done
          } >> $GITHUB_STEP_SUMMARY
