name: サイトマップ生成

on:
  workflow_call:
    inputs:
      repository:
        description: "Repository name"
        required: true
        type: string
      repository_no_register:
        description: "Alternative repository name if provided"
        required: false
        type: string

permissions:
  contents: read
  id-token: write
  pull-requests: write
  actions: read

jobs:
  sitemap:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      REPOSITORY: ${{ inputs.repository_no_register != '' && inputs.repository_no_register || inputs.repository }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Create sitemap
        run: |
          if [ ! -d "./${REPOSITORY}" ]; then
            echo "Error: ./${REPOSITORY} directory does not exist."
            exit 1
          fi

          files=$(find ./${REPOSITORY} -type f -name '*.html')

          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml

          for file in $files; do
            relative_path=${file#./out/${REPOSITORY}/}
            url="https://${REPOSITORY}/$relative_path"
            lastmod=$(stat -c %y "$file" | TZ=Asia/Tokyo git log -1 --format="%ci" -- "$file")

            echo '  <url>' >> sitemap.xml
            echo "    <loc>$url</loc>" >> sitemap.xml
            echo "    <lastmod>$lastmod</lastmod>" >> sitemap.xml
            echo '  </url>' >> sitemap.xml
          done

          echo '</urlset>' >> sitemap.xml
