name: アップロード予約

on:
  pull_request:
    branches:
      - main
    types: [opened, edited, reopened, synchronize]

jobs:
  RESERVATION:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: api test
        run: |
          response=$(curl -X GET \
              -H 'Content-Type: application/json' \
              -H 'Authorization: Bearer ${{ secrets.CRON_JOB_TOKEN }}' \
              https://api.cron-job.org/jobs)
          echo "Data from API: $response"
          echo "$response" > data.json

      - name: Extract Job ID
        id: extract_job_id
        run: |
          JOB_ID=$(jq -r '.jobs[] | select(.title == "feliamo") | .jobId' data.json)
          echo "Job ID: $JOB_ID"
          echo "job_id=$JOB_ID" >> $GITHUB_ENV

      - name: Display Job ID
        run: |
          echo "Extracted Job ID: ${{ env.job_id }}"




      # - name: Register Cron job
      #   env:
      #     month: ${{ inputs.month }}
      #     day: ${{ inputs.day }}
      #     hour: ${{ inputs.hour }}
      #     minutes: ${{ inputs.minutes }}
      #   run: |
      #     echo "Registering the job with month=$month, day=$day, hour=$hour, minutes=$minutes..."
      #     curl -X PATCH \
      #       -H 'Content-Type: application/json' \
      #       -H "Authorization: Bearer ${{ secrets.CRON_TOKEN }}" \
      #       -d "{
      #         \"job\": {
      #           \"enabled\": true,
      #           \"schedule\": {
      #             \"hours\": [$hour],
      #             \"mdays\": [$day],
      #             \"minutes\": [$minutes],
      #             \"months\": [$month]
      #           }
      #         }
      #       }" \
      #       https://api.cron-job.org/jobs/${{ vars.CRON_ID }}
