name: Dependabot Auto Merge to Main

on:
  pull_request:
    branches:
      - patch  # patch ブランチへの PR が作成されたとき
    types:
      - opened
      - synchronize
      - reopened

permissions:
  pull-requests: write
  contents: write

jobs:
  merge-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable GitHub CLI authentication
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Create PR from patch to main
        if: github.actor == 'dependabot[bot]'
        run: |
          PR_URL=$(gh pr create --base main --head patch --title "Merge dependabot updates from patch to main" --body "Automated PR to merge updates from patch to main.")
          echo "Created PR: $PR_URL"

      - name: Auto-approve PR
        if: github.actor == 'dependabot[bot]'
        run: gh pr review --approve "$GITHUB_REF"

      - name: Auto-merge PR
        if: github.actor == 'dependabot[bot]'
        run: gh pr merge --auto --squash "$GITHUB_REF"
