name: Dependabot Auto Merge to Main

on:
  pull_request:
    branches:
      - patch  # patch ブランチへの PR が作成されたとき
    types:
      - opened
      - synchronize
      - reopened

permissions:
  pull-requests: write
  contents: write

jobs:
  merge-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create PR from patch to main
        if: github.actor == 'dependabot[bot]'
        uses: actions/github-script@v4
        with:
          script: |
            const { data: pullRequest } = await github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "Merge dependabot updates from patch to main",
              head: "patch",
              base: "main",
              body: "Automated PR to merge updates from patch to main."
            });
            return pullRequest.html_url;

      - name: Auto-approve PR
        if: github.actor == 'dependabot[bot]'
        uses: actions/github-script@v4
        with:
          script: |
            await github.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            });

      - name: Auto-merge PR
        if: github.actor == 'dependabot[bot]'
        uses: actions/github-script@v4
        with:
          script: |
            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              merge_method: 'squash'
            });
