name: アップロード予約

on:
  workflow_call:
    inputs:
      month:
        description: "month"
        required: true
        type: string
      day:
        description: "day"
        required: true
        type: string
      hour:
        description: "hour"
        required: true
        type: string
      minutes:
        description: "minutes"
        required: true
        type: string

jobs:
  RESERVATION:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Register Cron job
        env:
          month: ${{ inputs.month }}
          day: ${{ inputs.day }}
          hour: ${{ inputs.hour }}
          minutes: ${{ inputs.minutes }}
        run: |
          echo "Registering the job with month=$month, day=$day, hour=$hour, minutes=$minutes..."
          curl -X PATCH \
            -H 'Content-Type: application/json' \
            -H "Authorization: Bearer ${{ secrets.CRON_TOKEN }}" \
            -d "{
              \"job\": {
                \"enabled\": true,
                \"schedule\": {
                  \"hours\": [$hour],
                  \"mdays\": [$day],
                  \"minutes\": [$minutes],
                  \"months\": [$month]
                }
              }
            }" \
            https://api.cron-job.org/jobs/${{ vars.CRON_ID }}
