name: アップロード予約

on:
  workflow_dispatch:
    inputs:
      month:
        type: choice
        required: true
        description: 月
        options:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
      day:
        type: choice
        required: true
        description: 日
        options:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
          - 13
          - 14
          - 15
          - 16
          - 17
          - 18
          - 19
          - 20
          - 21
          - 22
          - 23
          - 24
          - 25
          - 26
          - 27
          - 28
          - 29
          - 30
          - 31
      hour:
        type: choice
        required: true
        description: 時間
        options:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
          - 13
          - 14
          - 15
          - 16
          - 17
          - 18
          - 19
          - 20
          - 21
          - 22
          - 23
      minutes:
        type: choice
        required: true
        description: 分
        options:
          - 00
          - 05
          - 10
          - 15
          - 20
          - 25
          - 30
          - 35
          - 40
          - 45
          - 50
          - 55

jobs:
  RESERVATION:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Check if the user is authorized
      env:
        USER_LOGIN: ${{ github.actor }}
        CODE_OWNERS: ${{ vars.CODE_OWNERS }}
      run: |
        echo "$USER_LOGIN が許可されたリストに含まれているか確認しています..."
        if ! echo "$CODE_OWNERS" | grep -q -w "$USER_LOGIN"; then
          echo "ユーザー $USER_LOGIN はこのワークフローを実行する権限がありません。"
          exit 1
        fi
        echo "ユーザー $USER_LOGIN は認証されました。続行します..."

      - name: Register Cron job
        env:
          month: ${{ github.event.inputs.month }}
          day: ${{ github.event.inputs.day }}
          hour: ${{ github.event.inputs.hour }}
          minutes: ${{ github.event.inputs.minutes }}
        run: |
          echo "Registering the job with month=$month, day=$day, hour=$hour, minutes=$minutes..."
          curl -X PATCH \
            -H 'Content-Type: application/json' \
            -H "Authorization: Bearer ${{ secrets.CRON_TOKEN }}" \
            -d "{
              \"job\": {
                \"enabled\": true,
                \"schedule\": {
                  \"hours\": [$hour],
                  \"mdays\": [$day],
                  \"minutes\": [$minutes],
                  \"months\": [$month]
                }
              }
            }" \
            https://api.cron-job.org/jobs/${{ vars.CRON_ID }}
