name: Reservation

on:
  workflow_call:
    inputs:
      repository:
        description: "対象ブランド"
        required: true
        type: string
      repository_no_register:
        description: "任意のブランドリポジトリ"
        required: false
        type: string
      month:
        description: "月"
        required: true
        type: string
      day:
        description: "日"
        required: true
        type: string
      hour:
        description: "時"
        required: true
        type: string
      minutes:
        description: "分"
        required: true
        type: string
    secrets:
      CRON_JOB_TOKEN_VALUE:
        description: "Cron Job API Token"
        required: true

jobs:
  RESERVATION:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    env:
      REPOSITORY: ${{ inputs.repository_no_register != '' && inputs.repository_no_register || inputs.repository }}

    steps:
      - name: CronJobリストを取得
        run: |
          response=$(curl -X GET \
              -H 'Content-Type: application/json' \
              -H 'Authorization: Bearer ${{ secrets.CRON_JOB_TOKEN_VALUE }}' \
              https://api.cron-job.org/jobs)
          echo "Data from API: $response"
          echo "$response" > data.json

      - name: ジョブIDを抽出
        id: extract_job_id
        run: |
          JOB_ID=$(jq -r '.jobs[] | select(.title == "${{ env.REPOSITORY }}") | .jobId' data.json)
          echo "Job ID: $JOB_ID"
          echo "job_id=$JOB_ID" >> $GITHUB_ENV

      - name: Display Job ID
        run: |
          echo "::notice:: Job ID: ${{ env.job_id }}"

      - name: CronJobの登録
        env:
          month: ${{ inputs.month }}
          day: ${{ inputs.day }}
          hour: ${{ inputs.hour }}
          minutes: ${{ inputs.minutes }}
        run: |
          curl -X PATCH \
            -H 'Content-Type: application/json' \
            -H "Authorization: Bearer ${{ secrets.CRON_JOB_TOKEN_VALUE }}" \
            -d "{
              \"job\": {
                \"enabled\": true,
                \"schedule\": {
                  \"hours\": [$hour],
                  \"mdays\": [$day],
                  \"minutes\": [$minutes],
                  \"months\": [$month]
                }
              }
            }" \
            https://api.cron-job.org/jobs/${{ env.job_id }}
            echo "CronJob API response: $response"

      - name: 結果の表示
        run: |
          # GitHubステップサマリーに情報を追加
          {
            echo "# 予約した日時"
            echo "| リポジトリ | 予約日時 | ステータス |"
            echo "| -- | -- | -- |"
            echo "| ${{ env.REPOSITORY }} | ${{ inputs.month }}月${{ inputs.day }}日${{ inputs.hour }}時${{ inputs.minutes }}分 | $response |"
          } >> $GITHUB_STEP_SUMMARY
