name: Submodules Update

on:
  workflow_call:
    inputs:
      repository:
        description: "Repository name"
        required: true
        type: string
      repository_no_register:
        description: "Alternative repository name if provided"
        required: false
        type: string
      branch_name:
        description: "Branch name to commit changes"
        required: false
        type: string
    secrets:
      GITHUB_TOKEN_VALUE:
        description: "GitHub Token"
        required: true
  workflow_dispatch:
    inputs:
      repository:
        type: choice
        description: "Target Submodules"
        required: true
        options:
          - "topards.jp"
          - "feliamo.jp"
          - "molak.jp"
          - "ns-collection.jp"
          - "lilmoon.jp"
          - "minette-lens.jp"
          - "mirage-c.jp"
          - "mimuco.jp"
          - "harne.jp"
          - "louer.jp"
          - "lumieu.jp"
          - "puuuuchu.jp"
          - "melady.jp"
          - "melloew.jp"
          - "faloom.jp"
          - "mimicharme.jp"
          - "lensbe.jp"
          - "clainel.jp"
          - "chapun.jp"
          - "resay.jp"
          - "michou.jp"
      repository_no_register:
        description: "対象ブランド（未登録）"
        default: ""

permissions:
  contents: write
  pull-requests: write

jobs:
  Update:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      REPOSITORY: ${{ inputs.repository_no_register && inputs.repository_no_register || inputs.repository }}

    steps:
      - name: Check if the user is authorized
        env:
          USER_LOGIN: ${{ github.actor }}
          CODE_OWNERS: ${{ vars.CODE_OWNERS }}
        run: |
          echo "$USER_LOGIN が許可されたリストに含まれているか確認しています..."
          if ! echo "$CODE_OWNERS" | grep -q -w "$USER_LOGIN"; then
            echo "ユーザー $USER_LOGIN はこのワークフローを実行する権限がありません。"
            exit 1
          fi
          echo "ユーザー $USER_LOGIN は認証されました。続行します..."

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Git configuration
        run: |
          git config --global user.name ${{ vars.USERNAME }}
          git config --global user.email ${{ vars.MAILADDRESS }}
          git config --global url."https://${{ secrets.GITHUB_TOKEN_VALUE }}@github.com/".insteadOf "https://github.com/"

      - name: Check if submodule exists
        id: check_submodule
        run: |
          if git config --file .gitmodules --name-only --get-regexp path | grep -q "^submodule\.$REPOSITORY\.path$"; then
            echo "Submodule exists"
            echo "submodule_exists=true" >> $GITHUB_ENV
          else
            echo "Submodule does not exist"
            echo "submodule_exists=false" >> $GITHUB_ENV
          fi

      - name: Add submodule if not exists
        if: env.submodule_exists == 'false'
        run: |
          git submodule add https://github.com/pia-corp/${{ env.REPOSITORY }} ${{ env.REPOSITORY }}
          git submodule update --init --remote

      - name: Update submodules
        run: git submodule update --init --remote ${{env.REPOSITORY}}
        env:
          GITHUB_TOKEN_VALUE: ${{ secrets.GITHUB_TOKEN_VALUE }}

      - name: Check for submodule changes
        id: check_changes
        run: |
          if git diff --exit-code; then
            echo "No changes in submodules"
            echo "changed_files=false" >> $GITHUB_ENV
          else
            echo "Submodules have changed"
            echo "changed_files=true" >> $GITHUB_ENV
          fi

      - name: Checkout branch
        if: env.changed_files == 'true'
        run: |
          git checkout ${{ inputs.branch_name }}

      - name: Commit changes
        if: env.changed_files == 'true'
        id: commit
        run: |
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m "Automatically update submodules"
            echo "changed_files=true" >> $GITHUB_OUTPUT
          else
            echo "No changes to commit"
            echo "changed_files=false" >> $GITHUB_OUTPUT
          fi
          git push -u origin ${{ inputs.branch_name }}
